### ISSUE TITLE
PARQUET file can't be read

### ISSUE THREAD

**Issue by manticore-projects** [benleov/parquet-resultset#3]
Greetings!

First of all, big thank you for providing this library. Secondly, I am just starting with `DuckDB` and `Parquet` so it could be entirely my fault.

After creating a `parquet` file from a simple `ResultSet`, I can't import it into `DuckDB`:

```java
file = File.createTempFile(targetTableName + "_", ".parquet");
String namespace = "com.manticore.etl";

rs = st.executeQuery();

List<TransformerListener> listeners = new ArrayList<>();
ResultSetTransformer transformer = new ResultSetParquetTransformer();
InputStream inputStream = transformer.transform(rs, targetTableName, namespace, listeners);
FileWriter fileWriter = new FileWriter(file);
IOUtils.copy(inputStream, fileWriter, Charset.defaultCharset());
fileWriter.flush();
ileWriter.close();
```

```
D select count(*) from read_parquet('/tmp/ledger_account_entry_16076762837875017917.parquet');
Error: Invalid Error: TProtocolException: Invalid data
```

Am I doing something wrong in the java code?
Do I need to change the compression or deflate the file (I guess, it's SNAPPY compressed)?

I will appreciate any hint.
Thanks a lot in advance.

**Comment by manticore-projects** [comment]
Well, looks like invalid files were created since I also can't read my file using Python:

```python
from fastparquet import ParquetFile
pf = ParquetFile('/tmp/ledger_account_entry_16076762837875017917.parquet')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/are/.local/lib/python3.10/site-packages/fastparquet/api.py", line 143, in __init__
    self._parse_header(f, verify)
  File "/home/are/.local/lib/python3.10/site-packages/fastparquet/api.py", line 224, in _parse_header
    for rg in fmd[4]:
TypeError: 'NoneType' object is not iterable
```

**Comment by manticore-projects** [comment]
The Temporary file of the FileInputStream seems to be valid and correct.
The corruption comes from the `IOUtils.copy(inputStream, fileWriter, Charset.defaultCharset());` for whatever reason.

The whole approach of Writing a File first and then converting it to a InputStream in order to write a File is not helping me. I would try to write a File directly instead.

**Comment by manticore-projects** [comment]
Correct solution was:

```java
IOUtils.copy(inputStream, outputStream);
````
